# Generated by Django 5.2.8 on 2025-12-09 03:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=200, verbose_name='Nombre de la zona')),
                ('coordenadas_zona', models.JSONField(verbose_name='Coordenadas de la zona (GeoJSON)')),
                ('puntuacion_riesgo', models.FloatField(verbose_name='Puntuación de riesgo (0-100)')),
                ('total_alertas', models.IntegerField(default=0, verbose_name='Total de alertas')),
                ('alertas_panico', models.IntegerField(default=0, verbose_name='Alertas de pánico')),
                ('alertas_accidente', models.IntegerField(default=0, verbose_name='Alertas de accidente')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('periodo_inicio', models.DateField(verbose_name='Inicio del período')),
                ('periodo_fin', models.DateField(verbose_name='Fin del período')),
            ],
            options={
                'verbose_name': 'Estadística de Riesgo',
                'verbose_name_plural': 'Estadísticas de Riesgo',
                'ordering': ['-puntuacion_riesgo'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('rol', models.CharField(choices=[('repartidor', 'Repartidor'), ('operador', 'Operador'), ('administrador', 'Administrador')], default='repartidor', max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número telefónico debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('panico', 'Pánico'), ('accidente', 'Accidente Detectado')], max_length=20, verbose_name='Tipo de alerta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_atencion', 'En Atención'), ('atendida', 'Atendida'), ('cerrada', 'Cerrada'), ('falsa_alarma', 'Falsa Alarma')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('nivel_bateria', models.IntegerField(blank=True, null=True, verbose_name='Nivel de batería (%)')),
                ('datos_sensores', models.JSONField(blank=True, null=True, verbose_name='Datos de sensores')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('notas_iniciales', models.TextField(blank=True, verbose_name='Notas iniciales')),
                ('atendido_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'operador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(limit_choices_to={'rol': 'repartidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_911', models.CharField(blank=True, max_length=50, verbose_name='Folio 911')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del incidente')),
                ('contactos_notificados', models.BooleanField(default=False, verbose_name='Contactos notificados')),
                ('autoridades_contactadas', models.BooleanField(default=False, verbose_name='Autoridades contactadas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cerrado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('tiempo_respuesta', models.DurationField(blank=True, null=True, verbose_name='Tiempo de respuesta')),
                ('alerta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incidente', to='rappiSafe.alerta')),
                ('operador', models.ForeignKey(limit_choices_to={'rol': 'operador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(verbose_name='Acción realizada')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('operador', models.ForeignKey(limit_choices_to={'rol': 'operador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='rappiSafe.incidente')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepartidorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Última latitud')),
                ('ultima_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Última longitud')),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de ubicación')),
                ('nivel_bateria', models.IntegerField(blank=True, null=True, verbose_name='Nivel de batería (%)')),
                ('ultima_actualizacion_bateria', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de batería')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('emergencia', 'Emergencia'), ('offline', 'Offline')], default='offline', max_length=20, verbose_name='Estado')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('numero_identificacion', models.CharField(max_length=50, unique=True, verbose_name='Número de identificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_repartidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Repartidor',
                'verbose_name_plural': 'Perfiles de Repartidores',
            },
        ),
        migrations.CreateModel(
            name='RutaSegura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud origen')),
                ('origen_lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud origen')),
                ('destino_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud destino')),
                ('destino_lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud destino')),
                ('ruta_rapida', models.JSONField(verbose_name='Datos de ruta rápida')),
                ('ruta_segura', models.JSONField(verbose_name='Datos de ruta segura')),
                ('puntuacion_riesgo_rapida', models.FloatField(verbose_name='Riesgo ruta rápida')),
                ('puntuacion_riesgo_segura', models.FloatField(verbose_name='Riesgo ruta segura')),
                ('seleccionada', models.CharField(choices=[('rapida', 'Rápida'), ('segura', 'Segura')], max_length=10, verbose_name='Ruta seleccionada')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cálculo')),
                ('repartidor', models.ForeignKey(limit_choices_to={'rol': 'repartidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta Segura',
                'verbose_name_plural': 'Rutas Seguras',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAyudaPsicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('atendida', 'Atendida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('urgencia', models.IntegerField(default=5, verbose_name='Nivel de urgencia (1-10)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('atendido_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención')),
                ('notas_atencion', models.TextField(blank=True, verbose_name='Notas de atención')),
                ('repartidor', models.ForeignKey(limit_choices_to={'rol': 'repartidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_psicologicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Ayuda Psicológica',
                'verbose_name_plural': 'Solicitudes de Ayuda Psicológica',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Trayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precisión (metros)')),
                ('velocidad', models.FloatField(blank=True, null=True, verbose_name='Velocidad (m/s)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectorias', to='rappiSafe.alerta')),
            ],
            options={
                'verbose_name': 'Punto de Trayectoria',
                'verbose_name_plural': 'Trayectorias',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContactoConfianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número telefónico debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('relacion', models.CharField(blank=True, max_length=50, verbose_name='Relación')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('repartidor', models.ForeignKey(limit_choices_to={'rol': 'repartidor'}, on_delete=django.db.models.deletion.CASCADE, related_name='contactos_confianza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto de Confianza',
                'verbose_name_plural': 'Contactos de Confianza',
                'unique_together': {('repartidor', 'telefono')},
            },
        ),
    ]
