# Generated by Django 5.2.8 on 2025-12-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappiSafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidorprofile',
            name='nombre_aseguradora',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de la aseguradora'),
        ),
        migrations.AddField(
            model_name='repartidorprofile',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de póliza'),
        ),
        migrations.AddField(
            model_name='repartidorprofile',
            name='telefono_aseguradora',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono de la aseguradora'),
        ),
        migrations.AddField(
            model_name='repartidorprofile',
            name='tiene_seguro',
            field=models.BooleanField(default=False, verbose_name='¿Tiene seguro?'),
        ),
        migrations.AddField(
            model_name='repartidorprofile',
            name='vigencia_seguro',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia del seguro'),
        ),
    ]
